---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: loadbalancer-ips
  labels:
    advertise: bgp
spec:
  advertisements:
  - advertisementType: "Service"
    service:
      addresses:
      - LoadBalancerIP
    attributes:
      communities:
        standard: [ "64500:100" ]  # Optional: BGP community for traffic engineering
