apiVersion: v1
kind: Service
metadata:
  name: test-lb
  labels:
    io.cilium/lb-pool: main  # Use the IP pool
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
